### ISSUE TITLE
Newtonsoft.JSON 9.0

### ISSUE THREAD

**Issue by maleda** [RickStrahl/Westwind.ApplicationConfiguration#18]
I installed Westwind globalization usin NuGet  console. In my project there was already installed NewtonSoft.Json 9.0 so it was not installed. The LocalizationAdmin is not working (it does not connect to the databse giving me generic unknow error). But if i configure it manually webconfig, and create the tabte, command like DbRes.T("HelloWorld", "Resources") works.
I removed reference to NewtonSoft.Json 9.0 and added reference to NewtonSoft.Json 6.0. Now LocalizationAdmin is working (but unluckily i need version 9.0 for other part of my application).

May LocalizationAdmin works with NewtonSoft.Json 9.0 ?

**Comment by RickStrahl** [comment]
It should work as long as you recompile the projects. You may have to change the assembly redirects in the web.config to use the 9.0 assembly, but even that I don't think should be necessary.

The latest versions Westwind.Globalization should be using the 8.x versions of Newtonsoft.Json and this discussion would be better served in that repository. I'm closing this issue on this thread.
