### ISSUE TITLE
Raise exception on failure

### ISSUE THREAD

**Issue by holpit** [RickStrahl/Westwind.ApplicationConfiguration#7]
Hi Rick,
I've noted that with the xmlprovider, if the file is readonly and you attempt to change and write new data, the provider doesn't raise any exception and commit the changes internally.
So, you are sure that all data are saved, but they actually they aren't.
I have to set some settings to raise exceptions ?

Thank you,
Ivano

**Comment by RickStrahl** [comment]
Check the results from the Write() method which returns a boolean and the error message. There are no exceptions raised by this provider as you want configuration to work even if you can't write. Otherwise there'd be a lot of breaking scenarios.

Always check the result from the Write() method.
